[tools]
java = "latest"
lazydocker = "latest"
uv = "latest"
bun = "latest"
python = "latest"
gradle = "latest"
deno = "latest"
lazygit = "latest"
maven = "latest"
node = "latest"
bat = "latest"
eza = "latest"
go = "latest"
rust = "latest"
fzf = "latest"
rg = "latest"
ripgrep-all = "latest"
delta = "latest"
rye = "latest"
ruff = "latest"
tlrc = "latest"
scooter = "latest"
qsv = "latest"
yazi = "latest"
television = "latest"
tokei = "latest"
k9s = "latest"
kubectl = "latest"
kind = "latest"
glow = "latest"
atuin = "latest"
jq = "latest"
hyperfine = "latest"
bottom = "latest"
zig = "latest"
xh = "latest"
zellij = "latest"
docker-compose = "latest"
lychee = "latest"
rmz = "latest"
opencode = "latest"
minikube = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
crush = "latest"
gitleaks = "latest"
jules = "latest"
tmux = "latest"
jnv = "latest"
fastfetch = "latest"
shellcheck = "latest"
"npm:oxlint" = "latest"
"npm:oxfmt" = "latest"
trivy = "latest"
biome = "latest"
ast-grep = "latest"
"npm:tombi" = "latest"
starship = "latest"
yq = "latest"
vale = "latest"
marksman = "latest"
helix = "latest"
neovim = "latest"
pi = "latest"

[settings]
lockfile = true
python.uv_venv_auto = true
