return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  build = ":TSUpdate",
  event = "BufReadPost",
  opts = {
    ensure_installed = {
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "bash",
      "c",
      "zsh",
      "diff",
      "html",
      "http",
      "javascript",
      "typescript",
      "tsx",
      "prisma",
      "jsdoc",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "mermaid",
      "printf",
      "java",
      "python",
      "query",
      "regex",
      "vim",
      "vimdoc",
      "dockerfile",
    },
    highlight = { enable = false },
    indent = { enable = false },
  },
}
